# Generated by Django 5.1.3 on 2024-12-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FloexrtaDecorapp', '0005_navigationlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='url',
            field=models.CharField(max_length=1024),
        ),
    ]
