# Generated by Django 5.1.3 on 2024-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FloexrtaDecorapp', '0006_alter_navigationlink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
